travis:
  secure:
    BINSTAR_TOKEN: CVt9acwKB3NWn93W3c+pgchzMKDpIUZ/RksfN2tf+HqmB68mTR3pnu4/JT+07+tgEfImHDQfOb0YTqR1CYBxUbr7Pa8T1FL2Imuxf5SPHZDHofF0IsHul0A9y02z0Bk4t4W4GOcvyofz1MPSgow6EY1NXkOxQ/PWt1NlQ0l4p8nc8Px/58SAcHlFAzGel855ilGEz8gbfj47Q5BAKO+dudl6SgHhIeeTkAwwTrLJZOSA87yRYjhO69Jbehlr/3WHBvCyqCwqmFJ1ZDkFxxCUPmdAkSbBtX17vdirE3/Ju0xAX0VvG6jCYydsGdLZXfZlgJ1alAQRzJFuCHp0fZy0iWWmFNIQ4YUK+ozN+qIJAHAvnhYrusVCE5b4EscyM6eni6CcFPXhKr35wzjxR9YRg3qtQhQNOAowpRK03Z4iLDKhxvuOe3ad/ikkSE5QsnPd4BtIGvmiRFo7/xbwr09Hw1yoClhAd6gp18NiobCdD1BW1ib+bR57HFPn0lplkuqTGbm7pGVP/17g0h8ugGcBapS42SGRhGbOBoSBq1UHUc+OSjmWhz6t2WCoFfsg/9L7dAWaa+QiGVcjMKiK0r5cz1rBs6/NjDcyb0O7nsOZhrjdd1sUbhRDBrbrflTk1YF5LwylwVVp1eszMeIIMBq4ykI32k4tKs+lMMmkcPi1V2g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
